//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWDV_PR2 {
    
    
    public partial class artists {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SWDV_PR2.Site1 Master {
            get {
                return ((SWDV_PR2.Site1)(base.Master));
            }
        }
    }
}
